routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\GroupController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Livewire\Admin\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Front Routes
Route::get('/', function(){
    return view('front.welcome');
})->name('home');

// Admin Routes
Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::middleware(['is_admin'])->group(function(){
        Route::prefix('admin')->group(function () {
            Route::name('admin.')->group(function () {
                Route::get('/dashboard', Dashboard::class)->name('dashboard');
                Route::get('/users', [UserController::class, 'index'])->name('users');
                Route::resource('groups', GroupController::class);
                Route::resource('brands', BrandController::class);
                Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
                Route::controller(MessageController::class)->group(function () {
                    Route::get('/notifications', 'notifications')->name('notifications');
                    Route::get('/notify/{id}', 'notify')->name('notify');
                    Route::get('/markasread/{id}', 'markAsRead')->name('markasread');
                    Route::get('/markallasread', 'markAllAsRead')->name('markallasread');
                });
            });
        });
    });



});


Route::fallback(function () {
    return view('admin.components.error404');
});

resources/views/admin/warehouses/create.blade.php
@extends('layouts.admin')
@section('content')
    <h1 class="text-center p-3">{{__('Create Item')}}</h1>
    <div class="row d-flex justify-content-center">
        <div class="col-md-4">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{route('admin.groups.store')}}">
                @csrf
                <div class="mb-3">
                    <label for="name" class="form-label">{{__('Warehouse name')}}</label>
                    <input type="text" class="form-control" id="name" name="name"  value="{{old('name')}}">
                </div>
                <div class="mb-3">
                    <label for="address" class="form-label">{{__('Address')}}</label>
                    <input type="text" class="form-control" id="address" name="address"  value="{{old('address')}}">
                </div>
                <div class="mb-3">
                    <label for="group_id" class="form-label">{{__('Group name')}}</label>
                    <input type="text" class="form-control" id="group_id" name="group_id"  value="{{old('group_id')}}">
                </div>
                <button type="submit" class="btn btn-primary">{{__('Submit')}}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/warehouses/edit.blade.php
@extends('layouts.admin')
@section('content')
    <h1 class="text-center p-3">{{__('Update Item')}}</h1>
    <div class="row">
        <div class="col-md-6">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{route('admin.groups.update',$group->id)}}">
                @method('PUT')
                @csrf
                <div class="mb-3">
                    <label for="name" class="form-label">{{__('Group name')}}</label>
                    <input type="text" class="form-control" id="name" name="name"  value="{{$group->name}}">
                </div>
                <button type="submit" class="btn btn-primary">{{__('Update')}}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/warehouses/index.blade.php
@extends('layouts.admin ')
@section('content')
    <div class="container">
        <table class="table">
            <caption>List of Groups</caption>
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{{_('name')}}</th>
                <th colspan="3" class="text-center" scope="col">{{__('Actions')}}</th>

            </tr>
            </thead>

            <tbody>
            <div class="d-flex flex-row-reverse"><a href="{{route('admin.groups.create')}}" class="btn bg-primary text-white m-3 ">{{__('Add Item')}}</a></div>

            @foreach($groups as $group)
                <tr>
                    <th scope="row">{{($groups->currentpage()-1)*$groups->perpage()+$loop->index+1}}</th>
                    <td>{{$group->name}}</td>
                    <td>
                        <a href="{{route('admin.groups.show',$group->id)}}">
                            <i class="fa fa-eye"  aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{{route('admin.groups.edit',['group'=>$group->id])}}">
                            <i class="fas fa-pencil-alt" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>
                        <form method="post" action="{{route('admin.groups.destroy',['group'=>$group->id])}}">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger">

                                <i class="fas fa-trash-alt" aria-hidden="true"></i>
                            </button>

                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>

        </table>

        {{$groups->links()}}
    </div>
@endsection

resources/views/admin/warehouses/show.blade.php
@extends('layouts.admin')
@section('content')
    <h1 class="text-center p-3">Information about Group</h1>
    <div class=""><a href="{{route('admin.groups.index')}}" class="btn bg-danger text-white m-3 "><b class="font-size-20">&#8249&#8249&nbsp</b>{{__('Back')}}</a></div>
    <div class="container row  " style="height: 60vh">
        <div class="col-md-6  " style="height: 50%">
            <table class="table">
                <tr>
                    <td>{{__('Group Name')}}</td>
                    <td>{{$group->name}}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection